name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Tarea quejas boyaca/back"
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias (backend)
        run: npm install

      - name: Ejecutar pruebas (backend)
        run: npm test

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "Tarea quejas boyaca/front"
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias (frontend)
        run: npm install

      - name: Ejecutar pruebas (frontend)
        run: npm test
